name: Linter para validar padrão de código

on: [pull_request, push]

jobs:
  lint-styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Push to Github Container Registry
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: ${{ steps.extract_branch.outputs.branch }}
          file: Dockerfile
          target: production
          push: true
          tags: 'ghcr.io/${{ github.repository }}:${{ steps.extract_branch.outputs.branch }}'
